<a href="https://colab.research.google.com/github/Yanhuijun1911/PythonData/blob/main/Numpy_mini_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Investigate, wrangle, add new data to the dataframe, filter and correlate

The following data file contains data about student scores in math, reading and writing.  The exam scores are assumed to be percentages. It also contains data about gender, ethnicity, parental education, whether the student qualifies for free school food and whether or not the student has taken a preparation course for the exams.  The data set has already been cleaned. 

1.  Investigate the data set.

2.  Create numpy arrays to hold each of the three sets of scores.  
Create a new numpy array to hold the average exam score (of the three scores for each student)
Add the new numpy array as a new column in the dataframe.

3.  Filter the original dataset into a new dataframe containing just the females.  Calculate the average exam scores for all rows in this new dataframe and then find the mean of the average column.

4.  Do the same for the males.

5.  Use the original dataset to find the correlation coefficient for reading and maths.  How closely do they correlate?  Write what you find in a text box below the code.

6.  Do the same for reading and writing. What do you find?

7.  You might want to filter on different criteria and check correlation (e.g. those on free school meals, or those who had prepared, etc)







The dataset can be accessed here:  https://raw.githubusercontent.com/lilaceri/Working-with-data-/main/Data%20Sets%20for%20code%20divisio/exams.csv.  This is a .csv file.

**NOTE:** Some useful references are included at the bottom of this spreadsheet.

Use the code cell below to work your code.

In [10]:
from numpy.ma.extras import corrcoef
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/lilaceri/Working-with-data-/main/Data%20Sets%20for%20code%20divisio/exams.csv"
df = pd.read_csv(url)
df.info()

math_score = df["math_score"].to_numpy(np.int64)
reading_score = df["reading_score"].to_numpy(np.int64)
writing_score = df["writing_score"].to_numpy(np.int64)

average_score = (math_score + reading_score + writing_score) / 3
df["average_score"] = average_score.tolist()
print(df)


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype 
---  ------              --------------  ----- 
 0   gender              1000 non-null   object
 1   ethnicity           1000 non-null   object
 2   parental_education  1000 non-null   object
 3   lunch               1000 non-null   object
 4   preparation_course  1000 non-null   object
 5   math_score          1000 non-null   int64 
 6   reading_score       1000 non-null   int64 
 7   writing_score       1000 non-null   int64 
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
     gender ethnicity  ... writing_score average_score
0    female   group E  ...            71     70.666667
1      male   group C  ...            69     72.000000
2    female   group B  ...            61     59.666667
3      male   group D  ...            59     59.666667
4    female   group C  ...            55     47.666667
..      ...       ...  ...        

In [11]:

female = df[df["gender"] == "female"]
print(female)
average_female = female["average_score"].to_numpy(np.float64)
print(average_female.mean())

     gender ethnicity  ... writing_score average_score
0    female   group E  ...            71     70.666667
2    female   group B  ...            61     59.666667
4    female   group C  ...            55     47.666667
5    female   group B  ...            61     60.000000
6    female   group D  ...            92     88.333333
..      ...       ...  ...           ...           ...
989  female   group D  ...            82     76.666667
991  female   group C  ...            77     74.000000
992  female   group C  ...            65     57.666667
994  female   group D  ...            80     75.333333
997  female   group C  ...            93     84.000000

[496 rows x 9 columns]
70.81989247311829


In [12]:
male = df[df["gender"] == "male"]
average_male = male["average_score"].to_numpy(np.float64)
print(male)
print(average_male.mean())

    gender ethnicity  ... writing_score average_score
1     male   group C  ...            69     72.000000
3     male   group D  ...            59     59.666667
7     male   group E  ...            70     78.666667
9     male   group C  ...            82     80.666667
13    male   group C  ...            81     84.000000
..     ...       ...  ...           ...           ...
993   male   group E  ...            69     75.333333
995   male   group B  ...            74     75.666667
996   male   group D  ...            82     83.666667
998   male   group B  ...            57     60.333333
999   male   group B  ...            40     39.000000

[504 rows x 9 columns]
65.99272486772487


In [13]:
coef_reading_math = corrcoef(reading_score, math_score)
print(coef_reading_math)

coef_reading_writing = corrcoef(reading_score, writing_score)
print(coef_reading_writing)

[[1.0 0.8145975152425367]
 [0.8145975152425367 1.0]]
[[1.0 0.9567686336066268]
 [0.9567686336066268 1.0]]


In [ ]:
#strong correlation. The correlation of reading & writing is stronger than that of reading & math.

In [20]:

#prepared = df[df["preparation_course"] == "completed"]
#average_prepared = prepared["average_score"].to_numpy(np.float64)
non_prepared = df[df["preparation_course"] == "none"]
average_non_prepared = non_prepared["average_score"].to_numpy(np.float64)
math_non_prepared = non_prepared["math_score"].to_numpy(np.float64)

coef_preparation = corrcoef(average_non_prepaged, math_non_prepared)
print(coef_preparation)


[[1.0 0.9237004066549152]
 [0.9237004066549152 1.0]]


### Helpful references
---

Filtering on criteria using df references:  
`filtered_df = df[df['column name' == value]]`  

Filtering on multiple criteria using df reference:  
`filtered_df = df[df['first column name' == value] & df[second column name] >= value]`

Numpy help sheet:  http://datacamp-community-prod.s3.amazonaws.com/da466534-51fe-4c6d-b0cb-154f4782eb54

