<a href="https://colab.research.google.com/github/Yanhuijun1911/PythonData/blob/main/Sea_Level_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using numpy to look for a correlation between time data and sea level rise
---

### Data Source
Global Average Absolute Sea Level Change, 1880-2014 from the US Environmental Protection Agency using data from CSIRO, 2015; NOAA, 2015.
https://datahub.io/core/sea-level-rise

The data describes annual sea levels from 1880 to 2013.  Measures are adjusted using two standards: Commonwealth Scientific and Industrial Research Organisation(CSIRO) and National Oceanic and Atmospheric Administration (NOAA)  

Raw Data file:  https://raw.githubusercontent.com/freeCodeCamp/boilerplate-sea-level-predictor/master/epa-sea-level.csv

For this exercise:
*  import the pandas library
*  import the numpy library
*  read the csv dataset containing data on sea-levels from the year 1880 to 2013 into a dataframe (df)
*  use df.head() and df.info() to inspect the data and the column data types



In [ ]:
import pandas as pd
import numpy as np

url = "https://raw.githubusercontent.com/freeCodeCamp/boilerplate-sea-level-predictor/master/epa-sea-level.csv"
df = pd.read_csv(url)
print(df.head())
print(df.info())

   Year  CSIRO Adjusted Sea Level  ...  Upper Error Bound  NOAA Adjusted Sea Level
0  1880                  0.000000  ...           0.952756                      NaN
1  1881                  0.220472  ...           1.173228                      NaN
2  1882                 -0.440945  ...           0.464567                      NaN
3  1883                 -0.232283  ...           0.665354                      NaN
4  1884                  0.590551  ...           1.464567                      NaN

[5 rows x 5 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Year                      134 non-null    int64  
 1   CSIRO Adjusted Sea Level  134 non-null    float64
 2   Lower Error Bound         134 non-null    float64
 3   Upper Error Bound         134 non-null    float64
 4   NOAA Adjusted Sea Level   21 non-null    

### Then
---
1.  Calculate some statistics on the level array, eg:
*  mean
*  standard deviation
*  total 

2.  Use the fact that the arrays are aligned (e.g. the first number in the level array is linked to the first year in the year array and display:

*  the year with the biggest rise in level
*  the year with the lowest rise in level

*(**Hint**:  to do this you can use a new numpy function np.where() )*
 ```
np.where(array == value_to_find)
```
*There is some reference material [here](https://thispointer.com/find-the-index-of-a-value-in-numpy-array/)*

**Note**: ```np.where(...)``` will return a tuple containing all indexes where that value was found.  You can print all, or you can print the first value (it is likely that there will only be one in this case) using [0][0].  *With the correct code you should get an answer of 2012*


3.  Calculate the Pearson product-moment correlation coefficient between year and the rise in sea level.  (*Expected output:  0.98 when rounded to 2 decimal places*)

In [ ]:
CSIRO = df["CSIRO Adjusted Sea Level"].to_numpy(np.float64)
print(CSIRO.mean())
print(CSIRO.std())
print(CSIRO.sum())


3.650340811880598
2.476399631426498
489.1456687920001


In [ ]:

year = df["Year"].to_numpy(np.int64)
print(year)
coef = np.corrcoef(year, CSIRO)
print(coef)

[1880 1881 1882 1883 1884 1885 1886 1887 1888 1889 1890 1891 1892 1893
 1894 1895 1896 1897 1898 1899 1900 1901 1902 1903 1904 1905 1906 1907
 1908 1909 1910 1911 1912 1913 1914 1915 1916 1917 1918 1919 1920 1921
 1922 1923 1924 1925 1926 1927 1928 1929 1930 1931 1932 1933 1934 1935
 1936 1937 1938 1939 1940 1941 1942 1943 1944 1945 1946 1947 1948 1949
 1950 1951 1952 1953 1954 1955 1956 1957 1958 1959 1960 1961 1962 1963
 1964 1965 1966 1967 1968 1969 1970 1971 1972 1973 1974 1975 1976 1977
 1978 1979 1980 1981 1982 1983 1984 1985 1986 1987 1988 1989 1990 1991
 1992 1993 1994 1995 1996 1997 1998 1999 2000 2001 2002 2003 2004 2005
 2006 2007 2008 2009 2010 2011 2012 2013]
[[1.         0.98475713]
 [0.98475713 1.        ]]


In [ ]:
biggest = np.where(CSIRO == CSIRO.max(),)
print(biggest)
year_biggest = df.at[biggest[0][0], "Year"]

print(year_biggest)


(array([132]),)
2012


In [ ]:
lowest = np.where(CSIRO == CSIRO.min())
print(lowest)
year_lowest = df.at[lowest[0][0], "Year"]
print(year_lowest)

(array([2]),)
1882


# Reflection
----

## What skills have you demonstrated in completing this notebook?

Your answer: 

1. use numpy to calculate statistics: mean, std, median
2. df.to_numpy(np.int64)
3. np.where(lowest) will print the array where the value is the lowest
4. np.at[lowest[0][0], "Year"]]== print the value where the value is the lowest

## What caused you the most difficulty?

Your answer: 

understanding the array in numpay